title: "niehe-he"
description: "Crafting elegant code & beautiful experiences"
baseurl: ""
url: "https://niehe-he.github.io"
github_username: niehe-he

markdown: kramdown
permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - vendor/
  - .gitignore
